### ISSUE TITLE
Request to be added to the gallery

### ISSUE THREAD

**Issue by DavidHaskiya** [projectblacklight/projectblacklight.github.com#7]
Hi,
Would be great if we could add Europeana Collections to the showcase gallery.

Title: Europeana Collections
URL: http://www.europeana.eu/portal/

Screenshot attached below

![europeanacollections_searchresults](https://cloud.githubusercontent.com/assets/6057040/15736019/45c0c72a-289d-11e6-9bbc-bee91d929f9c.jpg)

Let me know if you need anything else!

Cheers,
David Haskiya

**Comment by cbeer** [comment]
Perfect, thanks.
