### ISSUE TITLE
Brown University Library entry for showcase

### ISSUE THREAD

**Issue by hectorcorrea** [projectblacklight/projectblacklight.github.com#8]
Here is the information to add Brown University Library to the showcase section. Hopefully I included everything needed.

YAML for `source/_data/showcase.yml`

```
- name: Brown University Library
  id: library-brown-edu
  img_url: images/showcase/brown_library.png
  desc: Josiah searches most of the journal, magazine, and newspaper resources available through Brown’s library databases, as well as our catalog (which includes most of the library's books and other physical holdings).
  url: http://library.brown.edu/
```

Image for `images/showcase` directory.

![brown_library](https://cloud.githubusercontent.com/assets/568286/18850664/7d7dbe2e-8406-11e6-84d4-0a88769a28e7.png)

**Comment by cbeer** [comment]
Would you mind sending this as a pull request?

**Comment by hectorcorrea** [comment]
@cbeer I tried but I don't have write access to this repo.

**Comment by hectorcorrea** [comment]
@cbeer nevermind, PR submitted.

**Comment by hectorcorrea** [comment]
PR https://github.com/projectblacklight/projectblacklight.github.com/pull/9
